@startuml
left to right direction
skinparam packageStyle rectangle

actor "Письменник" as Writer
actor "Зовнішній сервіс моніторингу здоров'я" as HealthService <<Service>>
actor "Адміністратор" as Admin

rectangle "Помічник письменника" {
  usecase "UC-1: Аналіз якості відпочинку" as UC1
  usecase "UC-2: Ознайомлення з нормами безпеки праці" as UC2
  usecase "UC-3: Управління творчими проєктами" as UC3
  usecase "UC-4: Моніторинг особистих досягнень та отримання відзнак" as UC4
  usecase "UC-5: Коригування творчого плану" as UC5
  usecase "UC-6: Перегляд поточного творчого плану" as UC6
  usecase "UC-7: Отримання даних про стан здоров'я" as UC7

  Writer -- UC1
  Writer -- UC2
  Writer -- UC3
  Writer -- UC4
  Writer -- UC5
  Writer -- UC6

  Admin -- UC2
  Admin -- UC4

  UC1 ..> UC7 : <<include>>
  HealthService -- UC7

  UC5 ..> UC6 : <<include>>
  UC3 ..> UC6 : <<include>>
}
@enduml
